//go:build !ignore_autogenerated
// +build !ignore_autogenerated

// Code generated by jsonschemagen. DO NOT EDIT.

package v1alpha1

import (
	_ "embed"
)

//go:embed schemas/GetGitHubCommit.schema.json
var schemaGetGitHubCommit []byte

//go:embed schemas/GetGitHubCommitOutput.schema.json
var schemaGetGitHubCommitOutput []byte

//go:embed schemas/GetGitHubCommitSpec.schema.json
var schemaGetGitHubCommitSpec []byte

// JSONSchema returns the JSON Schema for GetGitHubCommit.
func (GetGitHubCommit) JSONSchema() []byte {
	return schemaGetGitHubCommit
}

// JSONSchema returns the JSON Schema for GetGitHubCommitOutput.
func (GetGitHubCommitOutput) JSONSchema() []byte {
	return schemaGetGitHubCommitOutput
}

// JSONSchema returns the JSON Schema for GetGitHubCommitSpec.
func (GetGitHubCommitSpec) JSONSchema() []byte {
	return schemaGetGitHubCommitSpec
}
